package vn.neo.api.mapper.primary;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import vn.neo.api.entity.primary.Operation;
import vn.neo.api.entity.primary.OperationExample;

@Mapper
public interface OperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    long countByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    int deleteByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    int deleteByPrimaryKey(BigDecimal operationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    int insertSelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    List<Operation> selectByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    Operation selectByPrimaryKey(BigDecimal operationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Operation record, @Param("example") OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    int updateByExample(@Param("record") Operation record, @Param("example") OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    int updateByPrimaryKeySelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.OPERATION
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    int updateByPrimaryKey(Operation record);
}