package vn.neo.api.mapper.primary;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.neo.api.entity.primary.UserInfo;
import vn.neo.api.entity.primary.UserInfoExample;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    int deleteByPrimaryKey(BigDecimal userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    UserInfo selectByPrimaryKey(BigDecimal userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE.USER_INFO
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    int updateByPrimaryKey(UserInfo record);
}