server:
  port: 9090
spring:
  datasource:
    username: furniture
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(LOAD_BALANCE=true)(FAILOVER=true)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=thanglv)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari
  datasource-log:
    username: furniture_log
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(LOAD_BALANCE=true)(FAILOVER=true)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=thanglv)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      pool-name: Hikari