package vn.neo.api.mapper.log;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import vn.neo.api.entity.log.LogAct;
import vn.neo.api.entity.log.LogActExample;

@Mapper
public interface LogActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    long countByExample(LogActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    int deleteByExample(LogActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    int insert(LogAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    int insertSelective(LogAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    List<LogAct> selectByExample(LogActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    LogAct selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    int updateByExampleSelective(@Param("record") LogAct record, @Param("example") LogActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    int updateByExample(@Param("record") LogAct record, @Param("example") LogActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    int updateByPrimaryKeySelective(LogAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FURNITURE_LOG.LOG_ACT
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    int updateByPrimaryKey(LogAct record);
}