package vn.neo.api.entity.log;

public class LogAct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE_LOG.LOG_ACT.ID
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE_LOG.LOG_ACT.REQ
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    private String req;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE_LOG.LOG_ACT.RES
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    private String res;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE_LOG.LOG_ACT.ID
     *
     * @return the value of FURNITURE_LOG.LOG_ACT.ID
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE_LOG.LOG_ACT.ID
     *
     * @param id the value for FURNITURE_LOG.LOG_ACT.ID
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE_LOG.LOG_ACT.REQ
     *
     * @return the value of FURNITURE_LOG.LOG_ACT.REQ
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    public String getReq() {
        return req;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE_LOG.LOG_ACT.REQ
     *
     * @param req the value for FURNITURE_LOG.LOG_ACT.REQ
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    public void setReq(String req) {
        this.req = req;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE_LOG.LOG_ACT.RES
     *
     * @return the value of FURNITURE_LOG.LOG_ACT.RES
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    public String getRes() {
        return res;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE_LOG.LOG_ACT.RES
     *
     * @param res the value for FURNITURE_LOG.LOG_ACT.RES
     *
     * @mbg.generated Mon Nov 15 22:18:33 ICT 2021
     */
    public void setRes(String res) {
        this.res = res;
    }
}