package vn.neo.api.entity.primary;

import java.math.BigDecimal;
import java.util.Date;

public class Operation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.OPERATION.OPERATION_ID
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    private BigDecimal operationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.OPERATION.CREATED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.OPERATION.CREATED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.OPERATION.LAST_MODIFIED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.OPERATION.LAST_MODIFIED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    private Date lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.OPERATION.NAME
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.OPERATION.OPERATION_ID
     *
     * @return the value of FURNITURE.OPERATION.OPERATION_ID
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public BigDecimal getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.OPERATION.OPERATION_ID
     *
     * @param operationId the value for FURNITURE.OPERATION.OPERATION_ID
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public void setOperationId(BigDecimal operationId) {
        this.operationId = operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.OPERATION.CREATED_BY
     *
     * @return the value of FURNITURE.OPERATION.CREATED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.OPERATION.CREATED_BY
     *
     * @param createdBy the value for FURNITURE.OPERATION.CREATED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.OPERATION.CREATED_DATE
     *
     * @return the value of FURNITURE.OPERATION.CREATED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.OPERATION.CREATED_DATE
     *
     * @param createdDate the value for FURNITURE.OPERATION.CREATED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.OPERATION.LAST_MODIFIED_BY
     *
     * @return the value of FURNITURE.OPERATION.LAST_MODIFIED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.OPERATION.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for FURNITURE.OPERATION.LAST_MODIFIED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.OPERATION.LAST_MODIFIED_DATE
     *
     * @return the value of FURNITURE.OPERATION.LAST_MODIFIED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.OPERATION.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for FURNITURE.OPERATION.LAST_MODIFIED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.OPERATION.NAME
     *
     * @return the value of FURNITURE.OPERATION.NAME
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.OPERATION.NAME
     *
     * @param name the value for FURNITURE.OPERATION.NAME
     *
     * @mbg.generated Wed Nov 17 22:07:12 ICT 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}