package vn.neo.api.entity.primary;

import java.math.BigDecimal;
import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.ROLE.ROLE_ID
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    private BigDecimal roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.ROLE.CREATED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.ROLE.CREATED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.ROLE.LAST_MODIFIED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.ROLE.LAST_MODIFIED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    private Date lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.ROLE.ROLE_NAME
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.ROLE.ROLE_ID
     *
     * @return the value of FURNITURE.ROLE.ROLE_ID
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public BigDecimal getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.ROLE.ROLE_ID
     *
     * @param roleId the value for FURNITURE.ROLE.ROLE_ID
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.ROLE.CREATED_BY
     *
     * @return the value of FURNITURE.ROLE.CREATED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.ROLE.CREATED_BY
     *
     * @param createdBy the value for FURNITURE.ROLE.CREATED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.ROLE.CREATED_DATE
     *
     * @return the value of FURNITURE.ROLE.CREATED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.ROLE.CREATED_DATE
     *
     * @param createdDate the value for FURNITURE.ROLE.CREATED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.ROLE.LAST_MODIFIED_BY
     *
     * @return the value of FURNITURE.ROLE.LAST_MODIFIED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.ROLE.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for FURNITURE.ROLE.LAST_MODIFIED_BY
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.ROLE.LAST_MODIFIED_DATE
     *
     * @return the value of FURNITURE.ROLE.LAST_MODIFIED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.ROLE.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for FURNITURE.ROLE.LAST_MODIFIED_DATE
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.ROLE.ROLE_NAME
     *
     * @return the value of FURNITURE.ROLE.ROLE_NAME
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.ROLE.ROLE_NAME
     *
     * @param roleName the value for FURNITURE.ROLE.ROLE_NAME
     *
     * @mbg.generated Wed Nov 17 22:07:29 ICT 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}