package vn.neo.api.entity.primary;

import java.math.BigDecimal;
import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.USER_ID
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private BigDecimal userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.CREATED_BY
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.CREATED_DATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.LAST_MODIFIED_BY
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private Date lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.EMAIL
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.NAME
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.PASSWORD
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.STATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private Long state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.USERNAME
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FURNITURE.USER_INFO.CUSTOMER_ID
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    private BigDecimal customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.USER_ID
     *
     * @return the value of FURNITURE.USER_INFO.USER_ID
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.USER_ID
     *
     * @param userId the value for FURNITURE.USER_INFO.USER_ID
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.CREATED_BY
     *
     * @return the value of FURNITURE.USER_INFO.CREATED_BY
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.CREATED_BY
     *
     * @param createdBy the value for FURNITURE.USER_INFO.CREATED_BY
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.CREATED_DATE
     *
     * @return the value of FURNITURE.USER_INFO.CREATED_DATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.CREATED_DATE
     *
     * @param createdDate the value for FURNITURE.USER_INFO.CREATED_DATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.LAST_MODIFIED_BY
     *
     * @return the value of FURNITURE.USER_INFO.LAST_MODIFIED_BY
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for FURNITURE.USER_INFO.LAST_MODIFIED_BY
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.LAST_MODIFIED_DATE
     *
     * @return the value of FURNITURE.USER_INFO.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for FURNITURE.USER_INFO.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.EMAIL
     *
     * @return the value of FURNITURE.USER_INFO.EMAIL
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.EMAIL
     *
     * @param email the value for FURNITURE.USER_INFO.EMAIL
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.NAME
     *
     * @return the value of FURNITURE.USER_INFO.NAME
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.NAME
     *
     * @param name the value for FURNITURE.USER_INFO.NAME
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.PASSWORD
     *
     * @return the value of FURNITURE.USER_INFO.PASSWORD
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.PASSWORD
     *
     * @param password the value for FURNITURE.USER_INFO.PASSWORD
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.STATE
     *
     * @return the value of FURNITURE.USER_INFO.STATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.STATE
     *
     * @param state the value for FURNITURE.USER_INFO.STATE
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.USERNAME
     *
     * @return the value of FURNITURE.USER_INFO.USERNAME
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.USERNAME
     *
     * @param username the value for FURNITURE.USER_INFO.USERNAME
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FURNITURE.USER_INFO.CUSTOMER_ID
     *
     * @return the value of FURNITURE.USER_INFO.CUSTOMER_ID
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public BigDecimal getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FURNITURE.USER_INFO.CUSTOMER_ID
     *
     * @param customerId the value for FURNITURE.USER_INFO.CUSTOMER_ID
     *
     * @mbg.generated Mon Nov 15 22:13:59 ICT 2021
     */
    public void setCustomerId(BigDecimal customerId) {
        this.customerId = customerId;
    }
}